from pydantic import BaseModel


class UserResponse(BaseModel):
    fid: int
    username: str
    display_name: str
    pfp_url: str | None = None
    custody_address: str | None = None
    is_pro: bool = False
    is_admin: bool = False


class AuthUrlResponse(BaseModel):
    """Neynar-hosted SIWN authorization URL.

    Returned by GET /v1/auth/neynar-auth-url. Used by the native iOS app
    (`farcaster-audio/`), which opens this URL in a popup for the
    classic SIWN flow. The web/embed/dashboard surfaces use SIWF
    instead (POST /v1/auth/siwf/*); see `SiwfLoginRequest`.
    """

    authorization_url: str


class LoginRequest(BaseModel):
    signer_uuid: str
    fid: int
    # When true, the server returns the refresh token via an HttpOnly cookie
    # (`juke_refresh`) and omits it from the response body. Used by the
    # developer dashboard at juke.audio to mitigate XSS exfiltration of the
    # 30-day refresh window. Existing miniapp/embed callers default to false
    # and continue to receive the body-based refresh token unchanged.
    use_cookie: bool = False


class LoginResponse(BaseModel):
    jwt: str
    refresh_token: str | None = None
    expires_at: str
    user: UserResponse


class RefreshRequest(BaseModel):
    # Optional: the refresh token may instead arrive via the `juke_refresh`
    # HttpOnly cookie. If both are present, the cookie wins.
    refresh_token: str | None = None


class SiwfNonceResponse(BaseModel):
    """Server-issued single-use nonce for a SIWF sign-in attempt.

    The client passes this verbatim into the SIWE message generated by
    the Farcaster client. The backend rejects sign-in submissions whose
    nonce was never issued, was already consumed, or has expired
    (10-minute TTL).
    """

    nonce: str


class SiwfLoginRequest(BaseModel):
    """Body for POST /v1/auth/siwf/login.

    Carries the SIWE message the user signed in their Farcaster client
    plus the EIP-191 signature. The server parses + cryptographically
    verifies the message (siwe-py), confirms the recovered address
    resolves to a Farcaster FID via Neynar, and mints a Juke JWT.

    `use_cookie` semantics match `LoginRequest`.
    """

    message: str
    signature: str
    use_cookie: bool = False


class RegisterAuthAddressRequest(BaseModel):
    auth_address: str


class RegisterAuthAddressResponse(BaseModel):
    auth_address: str
    status: str
    approval_url: str | None = None


class AuthAddressStatusResponse(BaseModel):
    auth_address: str
    status: str
    fid: int | None = None


class InvalidateAuthAddressRequest(BaseModel):
    auth_address: str
